/pure_pursuit_node:
  ros__parameters:
    drive_flag: true
    kp: 0.75
    look_ahead: 1.8
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    scale: 0.77
    ttc: 2.0
    use_sim_time: false
    vel_inter: 4.0
    vel_max: 6.0
    vel_min: 3.0
